POST {{baseUrl}}/workouts/start
Accept: application/json
Content-Type: application/json

> {%
    client.global.set('workoutId', response.body.value);
%}

### Finish workout
POST {{baseUrl}}/workouts/{{workoutId}}/finish
Accept: application/json
Content-Type: application/json


### Record a set
POST {{baseUrl}}/workouts/{{workoutId}}/sets
Accept: application/json
Content-Type: application/json

{
  "exerciseName": "Bench Press",
  "repetitions": 12,
  "weight": 120.0
}
